### ISSUE TITLE
Oracle 

### ISSUE THREAD

**Issue by global4g** [govolution/betterdefaultpasslist#4]
Can you update oracle with below ?
Source : http://www.petefinnigan.com/default/oracle_default_passwords.htm

BRIO_ADMIN:BRIO_ADMIN
BRUGERNAVN:ADGANGSKODE
BRUKERNAVN:PASSWORD
BSC:BSC
BUG_REPORTS:BUG_REPORTS
CALVIN:HOBBES
CATALOG:CATALOG
CCT:CCT
CDEMO82:CDEMO82
CDEMO82:CDEMO83
CDEMO82:UNKNOWN
CDEMOCOR:CDEMOCOR
CDEMORID:CDEMORID
CDEMOUCB:CDEMOUCB
CDOUGLAS:CDOUGLAS
CE:CE
CENTRA:CENTRA
CENTRAL:CENTRAL
CIDS:CIDS
CIS:CIS
CIS:ZWERG
CISINFO:CISINFO
CISINFO:ZWERG
CLARK:CLOTH
CLKANA:.
CLKRT:.
CN:CN
COMPANY:COMPANY
COMPIERE:COMPIERE
CQSCHEMAUSER:PASSWORD
CQUSERDBUSER:PASSWORD
CRP:CRP
CS:CS
CSC:CSC
CSD:CSD
CSE:CSE
CSF:CSF
CSI:CSI
CSL:CSL
CSMIG:CSMIG
CSP:CSP
CSR:CSR
CSS:CSS
CTXDEMO:CTXDEMO
CTXSYS:.
CTXSYS:CHANGE_ON_INSTALL
CTXSYS:CTXSYS
CTXSYS:UNKNOWN
CUA:CUA
CUE:CUE
CUF:CUF
CUG:CUG
CUI:CUI
CUN:CUN
CUP:CUP
CUS:CUS
CZ:CZ
DATA_SCHEMA:LASKJDF098KSDAF09
DBI:MUMBLEFRATZ
MDDEMO_MGR:MDDEMO_MGR
MDSYS:MDSYS
ME:ME
MFG:MFG
MGR:MGR
MGWUSER:MGWUSER
MIGRATE:MIGRATE
MILLER:MILLER
MMO2:MMO2
MMO2:MMO3
MMO2:UNKNOWN
MODTEST:YES
MOREAU:MOREAU
MRP:MRP
MSC:MSC
MSD:MSD
MSO:MSO
MSR:MSR
MTS_USER:MTS_PASSWORD
MTSSYS:MTSSYS
MWA:MWA
MXAGENT:MXAGENT
NAMES:NAMES
NEOTIX_SYS:NEOTIX_SYS
NNEUL:NNEULPASS
NOM_UTILISATEUR:MOT_DE_PASSE
NOMEUTENTE:PASSWORD
NOME_UTILIZADOR:SENHA
NUME_UTILIZATOR:PAROL
OAIHUB902:.
OAS_PUBLIC:OAS_PUBLIC
OAS_PUBLIC:9300C0977D7DC75E
OCITEST:OCITEST
OCM_DB_ADMIN:.
OCM_DB_ADMIN:OCM_DB_ADMIN
ODM:ODM
ODM_MTR:MTRPW
ODS:ODS
ODS_SERVER:ODS_SERVER
ODSCOMMON:ODSCOMMON
OE:CHANGE_ON_INSTALL
OE:UNKNOWN
OE:OE
OEM_REPOSITORY:1FF89109F7A16FEF
OEMADM:OEMADM
OEMREP:OEMREP
OKB:OKB
OKC:OKC
OKE:OKE
OKI:OKI
OKO:OKO
OKR:OKR
OKS:OKS
OKX:OKX
OLAPDBA:OLAPDBA
OLAPSVR:INSTANCE
OLAPSVR:OLAPSVR
OLAPSYS:MANAGER
OLAPSYS:OLAPSYS
OMWB_EMULATION:ORACLE
ONT:ONT
OO:OO
OPENSPIRIT:OPENSPIRIT
OPI:OPI
ORACACHE:.
ORACACHE:ORACACHE
ORACLE:ORACLE
ORADBA:ORADBAPASS
ORANGE:3D9B7E34A4F7D4E9
ORAPROBE:ORAPROBE
ORAREGSYS:ORAREGSYS
ORASSO:ORASSO
ORASSO_DS:ORASSO_DS
ORASSO_PA:ORASSO_PA
ORASSO_PS:ORASSO_PS
ORASSO_PUBLIC:ORASSO_PUBLIC
ORASTAT:ORASTAT
ORCLADMIN:WELCOME
ORDCOMMON:ORDCOMMON
DBSNMP:DBSNMP
DBVISION:DBVISION
DCM:.
DDIC:199220706
DEMO:DEMO
DEMO8:DEMO8
DEMO9:DEMO9
DES:DES
DES2K:DES2K
DEV2000_DEMOS:DEV2000_DEMOS
DIANE:PASSWO1
DIP:DIP
DISCOVERER_ADMIN:DISCOVERER_ADMIN
DISCOVERER5:.
DMSYS:DMSYS
DPF:DPFPASS
DSGATEWAY:.
DSGATEWAY:DSGATEWAY
DSSYS:DSSYS
DTSP:DTSP
EAA:EAA
EAM:EAM
EARLYWATCH:SUPPORT
EAST:EAST
EC:EC
ECX:ECX
EJB:EJB
EJSADMIN:EJSADMIN
EJSADMIN:EJSADMIN_PASSWORD
EMP:EMP
ENG:ENG
ENI:ENI
ESTOREUSER:ESTORE
EVENT:EVENT
EVM:EVM
EXAMPLE:EXAMPLE
EXFSYS:EXFSYS
EXTDEMO:EXTDEMO
EXTDEMO2:EXTDEMO2
FA:FA
FEM:FEM
FII:FII
FINANCE:FINANCE
FINPROD:FINPROD
FLM:FLM
FND:FND
FOO:BAR
FPT:FPT
FRM:FRM
FROSTY:SNOWMAN
FTE:FTE
FV:FV
GL:GL
GMA:GMA
GMD:GMD
GME:GME
GMF:GMF
GMI:GMI
GML:GML
GMP:GMP
GMS:GMS
GPFD:GPFD
GPLD:GPLD
GR:GR
HADES:HADES
HCPARK:HCPARK
HLW:HLW
HR:UNKNOWN
ABM:ABM
ADAMS:WOOD
ADLDEMO:ADLDEMO
ADMIN:JETSPEED
ADMIN:WELCOME
ADMINISTRATOR:ADMIN
ADMINISTRATOR:ADMINISTRATOR
AHL:AHL
AHM:AHM
AK:AK
ALHRO:XXX
ALHRW:XXX
ALR:ALR
AMS:AMS
AMV:AMV
ANDY:SWORDFISH
ANONYMOUS:ANONYMOUS
ANONYMOUS:Anonymous
AP:AP
APPLMGR:APPLMGR
APPLSYS:APPLSYS
APPLSYS:APPS
APPLSYS:FND
APPLSYSPUB:APPLSYSPUB
APPLSYSPUB:PUB
APPLSYSPUB:FNDPUB
APPLYSYSPUB:FNDPUB
APPLYSYSPUB:PUB
APPLYSYSPUB:D2E3EF40EE87221E
APPS:APPS
APPS_MRC:APPS
APPUSER:APPPASSWORD
AQ:AQ
AQDEMO:AQDEMO
AQJAVA:AQJAVA
AQUSER:AQUSER
AR:AR
ASF:ASF
ASG:ASG
ASL:ASL
ASO:ASO
ASP:ASP
AST:AST
ATM:SAMPLEATM
AUDIOUSER:AUDIOUSER
AURORA$JIS$UTILITY$:INVALID_ENCRYPTED_PASSWORD
AURORA$JIS$UTILITY$:INVALID
AURORA$ORB$UNAUTHENTICATED:INVALID
AURORA$ORB$UNAUTHENTICATED:INVALID_ENCRYPTED_PASSWORD
AX:AX
AZ:AZ
BC4J:BC4J
BEN:BEN
BIC:BIC
BIL:BIL
BIM:BIM
BIS:BIS
BIV:BIV
BIX:BIX
BLAKE:PAPER
BLEWIS:BLEWIS
BOM:BOM
HR:33EBE1C63D5B7FEF
HR:CHANGE_ON_INSTALL
HR:HR
HRI:HRI
HVST:HVST
HXC:HXC
HXT:HXT
IBA:IBA
IBE:IBE
IBP:IBP
IBU:IBU
IBY:IBY
ICDBOWN:ICDBOWN
ICX:ICX
IDEMO_USER:IDEMO_USER
IEB:IEB
IEC:IEC
IEM:IEM
IEO:IEO
IES:IES
IEU:IEU
IEX:IEX
IFSSYS:IFSSYS
IGC:IGC
IGF:IGF
IGI:IGI
IGS:IGS
IGW:IGW
IMAGEUSER:IMAGEUSER
IMC:IMC
IMEDIA:IMEDIA
IMT:IMT
INTERNAL:ORACLE
INTERNAL:SYS_STNT
INV:INV
IPA:IPA
IPD:IPD
IPLANET:IPLANET
ISC:ISC
ITG:ITG
JA:JA
JAKE:PASSWO4
JE:JE
JG:JG
JILL:PASSWO2
JL:JL
JMUSER:JMUSER
JOHN:JOHN
JONES:STEEL
JTF:JTF
JTM:JTM
JTS:JTS
JWARD:AIROPLANE
KWALKER:KWALKER
L2LDEMO:L2LDEMO
LBACSYS:LBACSYS
LIBRARIAN:SHELVES
MANPROD:MANPROD
MARK:PASSWO3
MASCARM:MANAGER
MASTER:PASSWORD
MDDATA:MDDATA
MDDEMO:MDDEMO
MDDEMO_CLERK:CLERK
MDDEMO_CLERK:MGR
WWWUSER:WWWUSER
XADEMO:XADEMO
XDB:CHANGE_ON_INSTALL
XDP:XDP
XLA:XLA
XNC:XNC
XNI:XNI
XNM:XNM
XNP:XNP
XNS:XNS
XPRT:XPRT
XTR:XTR
MDDEMO_MGR:MGR
SYSTEM:D_SYSTPW
SYSTEM:ORACLE8I
SYSTEM:0RACLE8
SYSTEM:0RACLE9
SYSTEM:0RACLE8I
SYSTEM:0RACL38
SYSTEM:0RACL39
SYSTEM:0RACL38I
SYS:0RACLE8
SYS:0RACLE9
SYS:0RACLE8I
SYS:0RACL38
SYS:0RACL39
SYS:0RACL38I
ORDPLUGINS:ORDPLUGINS
ORDSYS:ORDSYS
OSE$HTTP$ADMIN:Invalid
OSE$HTTP$ADMIN:INVALID
OSM:OSM
OSP22:OSP22
OSSAQ_HOST:.
OSSAQ_PUB:.
OSSAQ_SUB:.
OTA:OTA
OUTLN:OUTLN
OWA:OWA
OWA_PUBLIC:OWA_PUBLIC
OWF_MGR:.
OWF_MGR:OWF_MGR
OWNER:OWNER
OZF:OZF
OZP:OZP
OZS:OZS
PA:PA
PANAMA:PANAMA
PATROL:PATROL
PAUL:PAUL
PERFSTAT:PERFSTAT
PERSTAT:PERSTAT
PJM:PJM
PLANNING:PLANNING
PLEX:PLEX
PLSQL:SUPERSECRET
PM:CHANGE_ON_INSTALL
PM:UNKNOWN
PM:PM
PMI:PMI
PN:PN
PO:PO
PO7:PO7
PO8:PO8
POA:POA
POM:POM
PORTAL:.
PORTAL_APP:.
PORTAL_DEMO:.
PORTAL_DEMO:PORTAL_DEMO
PORTAL_PUBLIC:.
PORTAL_SSO_PS:PORTAL_SSO_PS
PORTAL30:PORTAL30
PORTAL30:PORTAL31
PORTAL30_ADMIN:PORTAL30_ADMIN
PORTAL30_DEMO:PORTAL30_DEMO
PORTAL30_PS:PORTAL30_PS
PORTAL30_PUBLIC:PORTAL30_PUBLIC
PORTAL30_SSO:PORTAL30_SSO
PORTAL30_SSO_ADMIN:PORTAL30_SSO_ADMIN
PORTAL30_SSO_PS:PORTAL30_SSO_PS
PORTAL30_SSO_PUBLIC:PORTAL30_SSO_PUBLIC
POS:POS
POWERCARTUSER:POWERCARTUSER
PRIMARY:PRIMARY
PSA:PSA
PSB:PSB
PSP:PSP
PUBSUB:PUBSUB
PUBSUB1:PUBSUB1
PV:PV
QA:QA
QDBA:QDBA
QP:QP
QS:CHANGE_ON_INSTALL
QS:QS
QS:UNKNOWN
QS_ADM:CHANGE_ON_INSTALL
QS_ADM:QS_ADM
QS_ADM:UNKNOWN
QS_CB:CHANGE_ON_INSTALL
QS_CB:QS_CB
QS_CB:UNKNOWN
QS_CBADM:CHANGE_ON_INSTALL
QS_CBADM:QS_CBADM
QS_CBADM:UNKNOWN
QS_CS:CHANGE_ON_INSTALL
QS_CS:QS_CS
QS_CS:UNKNOWN
QS_ES:CHANGE_ON_INSTALL
QS_ES:QS_ES
QS_ES:UNKNOWN
QS_OS:CHANGE_ON_INSTALL
QS_OS:QS_OS
QS_OS:UNKNOWN
QS_WS:CHANGE_ON_INSTALL
QS_WS:QS_WS
QS_WS:UNKNOWN
RE:RE
REP_MANAGER:DEMO
REP_OWNER:DEMO
REP_OWNER:REP_OWNER
REP_USER:DEMO
REPADMIN:REPADMIN
REPORTS_USER:OEM_TEMP
REPORTS:REPORTS
RG:RG
RHX:RHX
RLA:RLA
RLM:RLM
RMAIL:RMAIL
RMAN:RMAN
RRS:RRS
SAMPLE:SAMPLE
SAP:SAPR3
SAP:06071992
SAPR3:SAP
SCOTT:TIGER
SCOTT:TIGGER
SDOS_ICSAP:SDOS_ICSAP
SECDEMO:SECDEMO
SERVICECONSUMER1:SERVICECONSUMER1
SH:CHANGE_ON_INSTALL
SH:SH
SH:UNKNOWN
SITEMINDER:SITEMINDER
SI_INFORMTN_SCHEMA:SI_INFORMTN_SCHEMA
SLIDE:SLIDEPW
SPIERSON:SPIERSON
SSP:SSP
STARTER:STARTER
STRAT_USER:STRAT_PASSWD
SWPRO:SWPRO
SWUSER:SWUSER
SYMPA:SYMPA
SYS:CHANGE_ON_INSTALL
SYS:D_SYSPW
SYS:MANAGER
SYS:ORACLE
SYS:SYS
SYS:SYSPASS
SYS:MANAG3R
SYS:ORACL3
SYS:0RACLE
SYS:0RACL3
SYS:ORACLE8
SYS:ORACLE9
SYS:ORACLE8I
SYS:ORACLE9I
SYS:0RACLE9I
SYS:0RACL39I
SYSADM:SYSADM
SYSADMIN:.
SYSADMIN:SYSADMIN
SYSMAN:OEM_TEMP
SYSMAN:SYSMAN
SYSTEM:CHANGE_ON_INSTALL
SYSTEM:D_SYSPW
SYSTEM:MANAGER
SYSTEM:ORACLE
SYSTEM:SYSTEMPASS
SYSTEM:SYSTEM
SYSTEM:MANAG3R
SYSTEM:ORACL3
SYSTEM:0RACLE
SYSTEM:0RACL3
SYSTEM:ORACLE8
SYSTEM:ORACLE9
SYSTEM:ORACLE9I
SYSTEM:0RACLE9I
SYSTEM:0RACL39I
TAHITI:TAHITI
TALBOT:MT6CH5
TDOS_ICSAP:TDOS_ICSAP
TEC:TECTEC
TEST:PASSWD
TEST:TEST
TEST_USER:TEST_USER
TESTPILOT:TESTPILOT
THINSAMPLE:THINSAMPLEPW
TIBCO:TIBCO
TIP37:TIP37
TRACESVR:TRACE
TRAVEL:TRAVEL
TSDEV:TSDEV
TSUSER:TSUSER
TURBINE:TURBINE
UDDISYS:.
ULTIMATE:ULTIMATE
UM_ADMIN:UM_ADMIN
UM_CLIENT:UM_CLIENT
USER:USER
USER_NAME:PASSWORD
USER0:USER0
USER1:USER1
USER2:USER2
USER3:USER3
USER4:USER4
USER5:USER5
USER6:USER6
USER7:USER7
USER8:USER8
USER9:USER9
UTILITY:UTILITY
USUARIO:CLAVE
UTLBSTATU:UTLESTAT
VEA:VEA
VEH:VEH
VERTEX_LOGIN:VERTEX_LOGIN
VIDEOUSER:VIDEOUSER
VIF_DEVELOPER:VIF_DEV_PWD
VIRUSER:VIRUSER
VPD_ADMIN:AKF7D98S2
VRR1:VRR1
VRR1:VRR2
VRR1:UNKNOWN
WEBCAL01:WEBCAL01
WEBDB:WEBDB
WEBREAD:WEBREAD
WEBSYS:MANAGER
WEBUSER:YOUR_PASS
WEST:WEST
WFADMIN:WFADMIN
WH:WH
WIP:WIP
WIRELESS:.
WKADMIN:WKADMIN
WKPROXY:WKPROXY
WKPROXY:CHANGE_ON_INSTALL
WKSYS:CHANGE_ON_INSTALL
WKPROXY:UNKNOWN
WKSYS:WKSYS
WKUSER:WKUSER
WK_SYS:79DF7A1BD138CF11
WK_TEST:WK_TEST
WK_PROXY:3F9FBD883D787341
WMS:WMS
WMSYS:WMSYS
WOB:WOB
WPS:WPS
WSH:WSH
WSM:WSM
WWW:WWW

**Comment by govolution** [comment]
Thank you, I asked for permission, since they do not allow copying it directly. If I can not copy directly I look for other sources for the passwords. Hope they give their permission.

**Comment by govolution** [comment]
This one seems also to be good and more open... don't see a problem here:
http://www.vulnerabilityassessment.co.uk/accounts.default

**Comment by govolution** [comment]
... also: https://github.com/pwnieexpress/metasploit-framework/blob/master/data/wordlists/oracle_default_hashes.txt

**Comment by global4g** [comment]
Great,  metasploit also has oracle_default_userpass.txt.
I should have seen that earlier :)

On May 20, 2017 11:57 AM, "govolution" <notifications@github.com> wrote:

... also: https://github.com/pwnieexpress/metasploit-
framework/blob/master/data/wordlists/oracle_default_hashes.txt

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/govolution/betterdefaultpasslist/issues/4#issuecomment-302892016>,
or mute the thread

**Comment by govolution** [comment]
Yes, me too! And also some more for other services. Good that it is weekend :).

**Comment by govolution** [comment]
OK, added lot of stuff now, maybe more to come. Thx again for the hint :).

**Comment by global4g** [comment]
Thank you !

**Comment by govolution** [comment]
BTW Pete Finnigan just gave permission to use his original list.
